parameters:
  - name: 'tag'
  - name: 'lastTag'

jobs:
  - job: Build
    steps:
      - script: echo ${{ parameters.tag }} ~ ${{ parameters.lastTag }}
        displayName: check variable
      # Build artifacts
      - script: yarn
        displayName: Install Packages
#      - script: yarn lint
#        displayName: linting
      # Test just the changed packages
      - script: npm run test
        displayName: unit testing
      # Build just the changed packages
      - script: yarn run ci:build --since ${{ parameters.tag }}
        displayName: build

  - job: Package
    dependsOn: Build
    steps:
      # Run to package
#      - script: yarn install --production
#        displayName: prune dependencies
#      - script: cp -R node_modules ./dist
#        displayName: copy node modules

      - script: npm i npm-pack-zip
      # Create the files just for the changed packages, remove the --since flag if you want to zip all the packages
      - script:  yarn run ci:zip --since ${{ parameters.tag }}

      # publish package as artifact
      - task: CopyFiles@2
        inputs:
          Contents: '**\packages\**\*.zip'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
      - task: PublishPipelineArtifact@1
        displayName: publish package
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'build-${{ parameters.lastTag }}'
          publishLocation: 'pipeline'


